CREATE DATABASE IF NOT EXISTS fact_checker;

USE fact_checker;

DROP TABLE fact_checker.query;

CREATE TABLE IF NOT EXISTS fact_checker.job (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    question STRING NOT NULL,
	engines ID INT NOT NULL,
	status STRING NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fact_checker.scrapes (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	job_id INT NOT NULL FOREIGN KEY REFERENCES fact_checker.job(ID),
	engine_id INT NOT NULL,
	status STRING NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fact_checker.llm_query (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	job_id INT NOT NULL FOREIGN KEY REFERENCES fact_checker.job(ID),
	result STRING NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);